global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'qzd-api'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'api:3000'
        labels:
          service: qzd-api
