name: CI

on:
  pull_request:
    branches: ["main", "master", "develop", "dev"]
  push:
    branches: ["main"]

jobs:
  spec-governance:
    name: Spec Governance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install oasdiff
        run: |
          mkdir -p "$HOME/go/bin"
          GOBIN="$HOME/go/bin" go install github.com/oasdiff/oasdiff@v1.11.7
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
      - name: Lint OpenAPI specification
        run: pnpm oas:lint
      - name: Check for OpenAPI breaking changes
        run: ./scripts/check-openapi-breaking.sh origin/main

  build:
    runs-on: ubuntu-latest
    needs:
      - spec-governance
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
