name: Post Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  tag-release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      created: ${{ steps.push_tag.outputs.created }}
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Determine release tag
        id: tag
        shell: bash
        run: |
          set -eo pipefail
          REF="${{ github.event.pull_request.head.ref }}"
          TITLE="${{ github.event.pull_request.title }}"
          if [[ "$REF" == release/* ]]; then
            TAG="${REF#release/}"
          elif [[ "$TITLE" =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            TAG="v${BASH_REMATCH[1]}"
          else
            echo "Unable to determine release tag from PR metadata." >&2
            exit 1
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Push git tag
        id: push_tag
        shell: bash
        run: |
          set -eo pipefail
          TAG="${{ steps.tag.outputs.tag }}"
          if git rev-parse -q --verify "refs/tags/$TAG"; then
            echo "Tag $TAG already exists; skipping." >&2
            echo "created=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin "${{ github.event.repository.default_branch }}" --prune --tags
          git checkout "${{ github.event.repository.default_branch }}"
          git pull origin "${{ github.event.repository.default_branch }}"
          COMMIT=$(git rev-parse HEAD)
          git tag -a "$TAG" "$COMMIT" -m "Release $TAG"
          git push origin "$TAG"
          echo "created=true" >> "$GITHUB_OUTPUT"

  publish-images:
    needs: tag-release
    if: needs.tag-release.outputs.tag != '' && needs.tag-release.outputs.created == 'true'
    uses: ./.github/workflows/publish-images.yml
    with:
      tag: ${{ needs.tag-release.outputs.tag }}
    secrets: inherit
