name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release_target:
        description: 'Release version (e.g. 1.2.3) or semver bump (major, minor, patch)'
        required: true
        default: patch

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    name: Prepare release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Calculate next version
        id: bump
        run: |
          VERSION=$(node scripts/bump-version.mjs "${{ inputs.release_target }}")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        run: |
          pnpm dlx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0

      - name: Create release pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): v${{ steps.bump.outputs.version }}'
          branch: 'release/v${{ steps.bump.outputs.version }}'
          base: ${{ github.event.repository.default_branch }}
          title: 'chore(release): v${{ steps.bump.outputs.version }}'
          labels: release
          body: |
            ## Summary
            - prepare release v${{ steps.bump.outputs.version }}
            - update package versions and changelog

            ---
            _Automated release preparation._
